//! Markdown reporter

use super::Reporter;
use crate::scanners::{ScanReport, VulnSeverity};
use anyhow::Result;

pub struct MarkdownReporter;

impl Reporter for MarkdownReporter {
    fn print(report: &ScanReport) -> Result<()> {
        println!("{}", Self::format(report)?);
        Ok(())
    }

    fn format(report: &ScanReport) -> Result<String> {
        let mut output = String::new();

        // Header
        output.push_str("# Security Scan Report\n\n");
        output.push_str(&format!("**Target:** {}\n", report.target));
        output.push_str(&format!("**Timestamp:** {}\n", report.timestamp));
        output.push_str(&format!("**Tool:** Warden {}\n\n", env!("CARGO_PKG_VERSION")));

        // Summary
        output.push_str("## Summary\n\n");
        output.push_str("| Severity | Count |\n");
        output.push_str("|----------|-------|\n");
        output.push_str(&format!("| CRITICAL | {} |\n", report.summary.critical));
        output.push_str(&format!("| HIGH | {} |\n", report.summary.high));
        output.push_str(&format!("| MEDIUM | {} |\n", report.summary.medium));
        output.push_str(&format!("| LOW | {} |\n", report.summary.low));
        output.push_str(&format!("| INFO | {} |\n", report.summary.info));
        output.push_str(&format!("| **Total** | **{}** |\n\n", report.summary.total));

        // Findings
        if report.findings.is_empty() {
            output.push_str("## Findings\n\n");
            output.push_str("✅ No vulnerabilities found.\n\n");
        } else {
            output.push_str("## Findings\n\n");

            for (i, finding) in report.findings.iter().enumerate() {
                let emoji = match finding.severity {
                    VulnSeverity::Critical => "🔴",
                    VulnSeverity::High => "🔴",
                    VulnSeverity::Medium => "🟡",
                    VulnSeverity::Low => "🔵",
                    VulnSeverity::Info => "⚪",
                };

                output.push_str(&format!("### {} {}. {}\n\n", emoji, i + 1, finding.title));
                output.push_str(&format!("**Severity:** `{}`\n\n", finding.severity));

                if let Some(ref location) = finding.location {
                    output.push_str(&format!("**Location:** `{}`\n\n", location));
                }

                output.push_str(&format!("**Description:**\n\n{}\n\n", finding.description));

                if let Some(ref recommendation) = finding.recommendation {
                    output.push_str(&format!("**Recommendation:**\n\n{}\n\n", recommendation));
                }

                if let Some(ref cwe) = finding.cwe {
                    output.push_str(&format!("**CWE:** {}\n\n", cwe));
                }

                if let Some(ref owasp) = finding.owasp {
                    output.push_str(&format!("**OWASP:** {}\n\n", owasp));
                }

                output.push_str("---\n\n");
            }
        }

        // Footer
        output.push_str(&format!(
            "\n*Generated by [Warden](https://github.com/Pamacea/warden) v{}*\n",
            env!("CARGO_PKG_VERSION")
        ));

        Ok(output)
    }
}
