//! Markdown reporter

use super::Reporter;
use crate::scanners::{ScanReport, VulnSeverity};
use anyhow::Result;

pub struct MarkdownReporter;

impl Reporter for MarkdownReporter {
    fn print(report: &ScanReport) -> Result<()> {
        println!("{}", Self::format(report)?);
        Ok(())
    }

    fn format(report: &ScanReport) -> Result<String> {
        let mut output = String::new();

        // Header
        output.push_str("# Security Scan Report\n\n");
        output.push_str(&format!("**Target:** {}\n", report.target));
        output.push_str(&format!("**Timestamp:** {}\n", report.timestamp));
        output.push_str(&format!("**Tool:** Warden {}\n\n", env!("CARGO_PKG_VERSION")));

        // Summary
        output.push_str("## Summary\n\n");
        output.push_str("| Severity | Count |\n");
        output.push_str("|----------|-------|\n");
        output.push_str(&format!("| CRITICAL | {} |\n", report.summary.critical));
        output.push_str(&format!("| HIGH | {} |\n", report.summary.high));
        output.push_str(&format!("| MEDIUM | {} |\n", report.summary.medium));
        output.push_str(&format!("| LOW | {} |\n", report.summary.low));
        output.push_str(&format!("| INFO | {} |\n", report.summary.info));
        output.push_str(&format!("| **Total** | **{}** |\n\n", report.summary.total));

        // Findings
        if report.findings.is_empty() {
            output.push_str("## Findings\n\n");
            output.push_str("✅ No vulnerabilities found.\n\n");
        } else {
            output.push_str("## Findings\n\n");

            for (i, finding) in report.findings.iter().enumerate() {
                let emoji = match finding.severity {
                    VulnSeverity::Critical => "🔴",
                    VulnSeverity::High => "🔴",
                    VulnSeverity::Medium => "🟡",
                    VulnSeverity::Low => "🔵",
                    VulnSeverity::Info => "⚪",
                };

                output.push_str(&format!("### {} {}. {}\n\n", emoji, i + 1, finding.title));
                output.push_str(&format!("**Severity:** `{}`\n\n", finding.severity));

                if let Some(ref location) = finding.location {
                    output.push_str(&format!("**Location:** `{}`\n\n", location));
                }

                output.push_str(&format!("**Description:**\n\n{}\n\n", finding.description));

                if let Some(ref recommendation) = finding.recommendation {
                    output.push_str(&format!("**Recommendation:**\n\n{}\n\n", recommendation));
                }

                if let Some(ref cwe) = finding.cwe {
                    output.push_str(&format!("**CWE:** {}\n\n", cwe));
                }

                if let Some(ref owasp) = finding.owasp {
                    output.push_str(&format!("**OWASP:** {}\n\n", owasp));
                }

                output.push_str("---\n\n");
            }
        }

        // Footer
        output.push_str(&format!(
            "\n*Generated by [Warden](https://github.com/Pamacea/warden) v{}*\n",
            env!("CARGO_PKG_VERSION")
        ));

        Ok(output)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scanners::{Target, Vuln, VulnSeverity};

    #[test]
    fn test_markdown_format_empty_report() {
        let report = ScanReport::new(Target::Url("http://example.com".to_string()));
        let formatted = MarkdownReporter::format(&report).unwrap();

        assert!(formatted.contains("# Security Scan Report"));
        assert!(formatted.contains("**Target:**"));
        assert!(formatted.contains("**Timestamp:**"));
        assert!(formatted.contains("No vulnerabilities found"));
    }

    #[test]
    fn test_markdown_format_with_findings() {
        let mut report = ScanReport::new(Target::Url("http://example.com".to_string()));
        report.add_finding(Vuln {
            severity: VulnSeverity::Critical,
            title: "Critical Vulnerability".to_string(),
            description: "This is a critical issue".to_string(),
            location: Some("/api/test".to_string()),
            recommendation: Some("Apply patch immediately".to_string()),
            cwe: Some("CWE-79".to_string()),
            owasp: Some("A03:2021 - Injection".to_string()),
        });

        let formatted = MarkdownReporter::format(&report).unwrap();

        assert!(formatted.contains("## Findings"));
        assert!(formatted.contains("Critical Vulnerability"));
        assert!(formatted.contains("This is a critical issue"));
        assert!(formatted.contains("/api/test"));
        assert!(formatted.contains("Apply patch immediately"));
        assert!(formatted.contains("CWE-79"));
        assert!(formatted.contains("A03:2021"));
    }

    #[test]
    fn test_markdown_severity_emojis() {
        let mut report = ScanReport::new(Target::Url("http://example.com".to_string()));

        report.add_finding(Vuln {
            severity: VulnSeverity::Critical,
            title: "Critical".to_string(),
            description: "Test".to_string(),
            location: None,
            recommendation: None,
            cwe: None,
            owasp: None,
        });

        report.add_finding(Vuln {
            severity: VulnSeverity::High,
            title: "High".to_string(),
            description: "Test".to_string(),
            location: None,
            recommendation: None,
            cwe: None,
            owasp: None,
        });

        report.add_finding(Vuln {
            severity: VulnSeverity::Medium,
            title: "Medium".to_string(),
            description: "Test".to_string(),
            location: None,
            recommendation: None,
            cwe: None,
            owasp: None,
        });

        let formatted = MarkdownReporter::format(&report).unwrap();

        assert!(formatted.contains("🔴")); // Critical/High
    }

    #[test]
    fn test_markdown_summary_table() {
        let mut report = ScanReport::new(Target::Url("http://example.com".to_string()));

        report.add_finding(Vuln {
            severity: VulnSeverity::Critical,
            title: "Test".to_string(),
            description: "Test".to_string(),
            location: None,
            recommendation: None,
            cwe: None,
            owasp: None,
        });

        let formatted = MarkdownReporter::format(&report).unwrap();

        assert!(formatted.contains("## Summary"));
        assert!(formatted.contains("| CRITICAL | 1 |"));
        assert!(formatted.contains("| **Total** | **1** |"));
    }

    #[test]
    fn test_markdown_contains_footer() {
        let report = ScanReport::new(Target::Url("http://example.com".to_string()));
        let formatted = MarkdownReporter::format(&report).unwrap();

        assert!(formatted.contains("Generated by [Warden]"));
        assert!(formatted.contains("github.com/Pamacea/warden"));
    }
}
